name: Ipot
description: A plant manager.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
  cloud_firestore: ^0.14.1+2
  firebase_core: 0.5.0
  firebase_auth: 0.18.0+1
  flappy_search_bar: 1.4.1
  loading_animations: "^2.1.0"
  cupertino_icons: ^0.1.3
  firebase_database: 4.1.0

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: false

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
